site_name: Nautilis
repo_name: neumj/nautilis
repo_url: https://github.com/neumj/nautilis
copyright: Copyright &copy; 2024 - Neumann
    
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/diver.png
  favicon: assets/diver.png
  features:
    - content.tabs.link
    - navigation.footer
    - search.highlight

markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      type: datetime
      timezone: America/Los_Angeles
  - with-pdf:
      author: Neumann
      cover: true
      back_cover: false
      cover_title: Nautilis
      cover_subtitle: Neumann Dive Logs

extra:
  generator: false

nav:
    - Home: index.md
    - MJN:
      - Dive 130 - Hen Rock Cove: mjn/130-hen-rock.md
      - Dive 129 - Long Point: mjn/129-long-point.md
      - Dive 128 - Long Point: mjn/128-long-point.md
      - Dive 127 - Lions Head: mjn/127-lions-head.md
      - Dive 126 - Sea Fan Grotto: mjn/126-sea-fan-grotto.md
      - Dive 125 - Indian Rock: mjn/125-indian-rock.md
      - Dive 124 - Indian Rock: mjn/124-indian-rock.md
      - Dive 123 - Indian Rock: mjn/123-indian-rock.md
      - Dive 122 - Indian Rock: mjn/122-indian-rock.md
      - Dive 121 - Shaw's Cove: mjn/121-shaws-cove.md
    - Entries by Tags: tags.md